### ISSUE TITLE
Better way to get tasks

### ISSUE THREAD

**Issue by sindresorhus** [jenslind/piglet#10]
The current way tries to parse the Gruntfile. This is both slow and super fragile. It won't work on dynamically created tasks.

You could use https://github.com/sindresorhus/get-grunt-tasks instead.

**Comment by jenslind** [comment]
Yeah thats probably a better way of doing it! :star:
Though I think Grunt should implement an easier way of getting only the tasks, because parsing stdout is not optimal either. :)
